### PR TITLE
MDL-61486 tool_dataprivacy: Data registry retention period info

### PR DESCRIPTION
**Pull request by dmonllao**

### CODE REVIEW

**Comment by junpataleta** [comment]
Thanks for working on this, David. Looks good to me. Some comments:
1. In dataregistry.php, I am seeing the "Inherit" option in the Site level context. I remember from the previous meetings with the team that this should be removed.
2. I'm seeing the following ESLint warnings:

> /home/jun/moodles/dptool33/moodle/admin/tool/dataprivacy/amd/src/effective_retention_period.js
>   32:9  warning  Expected JSDoc for 'purposeRetentionPeriods' but found 'Associative'  valid-jsdoc
> 

There's also a preexisting warning, but might be worth fixing as well:

> /home/jun/moodles/dptool33/moodle/admin/tool/dataprivacy/amd/src/data_registry.js
>   298:13  warning  Missing JSDoc return type  valid-jsdoc

3. The following imports in \tool_dataprivacy\api are unnecessary and can be removed since these classes are already on the same level as the api class:

> use tool_dataprivacy\purpose;
> use tool_dataprivacy\category;
> use tool_dataprivacy\contextlevel;
> use tool_dataprivacy\context_instance;

4. In one of the meetings, it was agreed to use something like "Use default ([DEFAULT_VALUE])" instead of "Not set (Use default value)". We'll have to confirm this though with the team (sorry I don't recall the concrete details).

**Comment by dmonllao** [comment]
Hi Jun. I've pushed an updated patch with removed uses and js js-doc fixes. The first point you comment about should be fixed in https://tracker.moodle.org/browse/MDL-59720

**Comment by dmonllao** [comment]
Re 4. Sorry, I don't remember that requirement. I agree it would be ok but I would prefer to defer it to another issue; the retention period that is applied is displayed below that solves the main user need.

**Comment by dmonllao** [comment]
btw: you should be able to cherry pick to stables

**Comment by junpataleta** [comment]
Thanks, David. Merged and cherry-picked to stables.

**Pull request merged**
