### PR TITLE
 MDL-61830 tool_dataprivacy: Create the expired contexts review page

### PR DESCRIPTION
**Pull request by junpataleta**

### CODE REVIEW

**Comment by dmonllao** [comment]
Hi Jun,

Thanks it looks good, I couldn't finish reviewing the expired courses method (the one more performance-critical) but I will finish it tomorrow.

1.- If I access admin/tool/dataprivacy/datadeletion.php straight after upgrading I see "Nothing to display" maybe we could add an info message to explain that page purpose, something like this page lists the context which retention period has expired.... bal blabalabalbl
2.- I imagine that we deferred the possibility to discard an expired context from being deleted. Do we have an issue for it?

Changes I've implemented in https://github.com/dmonllao/moodle-tool_dataprivacy/commit/3807b8f244cb4ccfb417d3fa0765dea6690b0e72 (feel free to merge in your branch):
* "Delete selected" button appeared even if no context instances were listed
* There was no user context level
* Extend the default null $contextlevel to get_record_count_by_contextlevel
* Use purpose exporter instead of duplicating the formatted retention period logic
* Fixed a couple of calls to get_effective_context_purpose and get_effective_context_category as the second argument should be false, context_instance::NOT_SET, context_instance::INHERIT or a purpose id
* (unrelated to this patch) Added number of expired contexts updated when tasks are running

**Comment by junpataleta** [comment]
Thanks for the review, David! I agree with the refinements that you made. Great job!

I'm not quite sure though about displaying the expired user contexts. Perhaps @andrewnicols can further explain why only expired course-, course module- and block-level contexts only need to be removed.

Re: 1 - Done. I also have overridden print_nothing_to_display() in order to show a more meaningful message to the user for empty results.
Re: 2 - Not sure if there's already an issue about that. Probably none though.

**Comment by dmonllao** [comment]
Thanks Jun. Merged and commits cherry picked to stables.

**Comment by andrewnicols** [comment]
User contexts cannot explicitly expire at this time - we have nothing to base their expiry on.

**Comment by dmonllao** [comment]
We discussed this a couple of weeks ago https://github.com/moodlehq/moodle-tool_dataprivacy/blob/master/classes/expired_user_contexts.php

**Pull request merged**
