### PR TITLE
MDL-61798 tool_dataprivacy: Set userid for exports

### PR DESCRIPTION
**Pull request by andrewnicols**
Should cherry-pick cleanly to stables.

### CODE REVIEW

**Comment by andrewnicols** [comment]
@abgreeve, if you're around and want to peer review.

**Comment by junpataleta** [comment]
Hi Andrew, 

\core\task\adhoc_task::set_userid() has been introduced in 3.4. So we might need a different approach for this on 3.3.

**Comment by andrewnicols** [comment]
Thanks Jun - good catch,

I've pushed a second patch for 33 which runs ```cron_setup_user()``` as the intended request user.

**Comment by junpataleta** [comment]
Thanks, Andrew. Merged and cherry-picked to 34.

**Pull request merged**
