### PR TITLE
MDL-61271 tool_dataprivacy: Convert defaults button to action_link

### PR DESCRIPTION
**Pull request by junpataleta**
The core/single_button template is only available in Boost for 3.3.
Use action_link instead for the defaults button.

### CODE REVIEW

**Comment by dmonllao** [comment]
Hi Jun. Many thanks for fixing this. There are other references to single buttons that would need to be changed as well if we switch to action_links, single_button is actually part of a method signature so I would suggest to call single_button::render from tool_dataprivacy\output\data_registry_page::export_for_template instead and just {{{defaultsbutton}}}. This way once 33 is out of support we can just revert this patch. What do you think?

**Comment by junpataleta** [comment]
Thanks, David. It's fine for me, but perhaps apply the fix to 33 only so we won't have to revert the patch in the future. I'll whip up a patch tomorrow for 33 with the single_button::render() for the defaults button and check the other locations as well, if you're fine with this approach.

**Comment by junpataleta** [comment]
Hi David, 

I tried rendering the single_button HTML into the template directly and it is not aligned with the "Edit" action menu on Clean:
image

Seems that we can't do much about this as the single button element is being rendered as a button-type input, unlike in 34 and up.

Please let me know your preferred approach:
1. Fix this on 33 only using $output->render(single_button) and don't worry about the misalignment in Clean.
2. Merge the original patch to master and cherry-pick to stables. I don't think there's a need to convert the other single buttons to action links they are not really affected. If we want to be consistent and use action links for the navigation in categories and purposes crud pages, as well, then we could raise a separate issue to make \tool_dataprivacy\output\crud_element::get_navigation() to return an action_link instead (it's currently basically returning html string and not really an array of single_button objects).
3. Continue with the original patch and convert \tool_dataprivacy\output\crud_element::get_navigation() to return an array of action_links instead.

Personally, I'm leaning on 3. Though I'd also like to hear your thoughts.

**Comment by dmonllao** [comment]
The only problem with #3 is that the action link is really a link, not a button and we have to hardcode btn and btn-defualt. IMO either #1 or #3 is fine so feel free to go ahead with #3 if that is your preference.

**Comment by dmonllao** [comment]
Regarding the misaligment, yep, I saw it but I didn't spend time on fixing it, bs2 themes will be deprecated in 3.6 and I preferred to spend resources on other stuff

**Comment by junpataleta** [comment]
Thanks, David.

Going with Option 3. I added a commit with the original patch that converts the other single buttons to action links.

**Comment by dmonllao** [comment]
Thanks Jun. Merged, changes cherry picked to stables.

**Pull request merged**
